kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elastic-search-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
            storage: 10Gi
  storageClassName: elastic-search-nfs
  selector:
    matchLabels:
      type: elastic-search-claim
