kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-master-pvc 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: redis-master-nfs
  selector:
    matchLabels:
      type: redis-master-claim
