master:
  podSecurityContext:
    fsGroup: 1000
  containerSecurityContext:
    runAsUser: 1000
  persistence:
    existingClaim: redis-master-pvc
    enabled: true
replica:
  persistence:
    enabled: false 
