apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
spec:
  version: 7.9.0
  nodeSets:
  - name: master-nodes
    count: 1
    podTemplate:
      spec:
        securityContext:
          fsGroup: 0
          runAsUser: 1000
          runAsGroup: 1000
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              memory: 4Gi
              cpu: 0.5
            limits:
              memory: 4Gi
              cpu: 2
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0 
    config:
      node.master: true
      node.data: false
      node.ingest: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic-search-nfs
  - name: data-nodes
    count: 1
    podTemplate:
      spec:
        securityContext:
          fsGroup: 0
          runAsUser: 1000
          runAsGroup: 1000
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms2g -Xmx2g
          resources:
            requests:
              memory: 4Gi
              cpu: 0.5
            limits:
              memory: 4Gi
              cpu: 2
          image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0             
    config:
      node.master: false
      node.data: true
      node.ingest: false
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: elastic-search-data-nfs
