apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mysql-admin-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: mysql-admin.frankwang.cn 
      http:
        paths:
          - backend:
              serviceName: my-release-phpmyadmin
              servicePort: 80
            path: /(.*)
