apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zhihu-spider-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: zhihu-spider.yanqiw.qianyitian.com 
      http:
        paths:
          - backend:
              serviceName: zhihu-spider
              servicePort: 8080
            path: /(.*)
    - host: zhihu-spider.yanqiw-next.qianyitian.com 
      http:
        paths:
          - backend:
              serviceName: zhihu-spider
              servicePort: 8080
            path: /(.*)
    - host: zhihu-spider.frankwang.cn
      http:
        paths:
          - backend:
              serviceName: zhihu-spider
              servicePort: 8080
            path: /(.*)
